Modified assemble script

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -36,14 +36,17 @@ date
 LOCAL_SOURCE_DIR=/tmp/src
 DEPLOY_DIR=${HOME}
 
-echo "Pre assemble parameters"
-echo "LOCAL_SOURCE_DIR: $LOCAL_SOURCE_DIR"
-echo "DEPLOY_DIR: $DEPLOY_DIR"
-echo "ANGULAR_PACKAGE_NAME: ${ANGULAR_PACKAGE_NAME}"
-echo "ANGULAR_PACKAGE_TARBALL: ${ANGULAR_PACKAGE_TARBALL}"
-echo "ARTIFACTORY_REPO: ${ARTIFACTORY_REPO}"
-echo "NGINX_VERSION: ${NGINX_VERSION}"
-echo "ARTIFACTORY_TOKEN: ${ARTIFACTORY_TOKEN}"
+echo "Pre assemble parameters\n" +
+     "-----------------------\n" +
+echo "LOCAL_SOURCE_DIR: $LOCAL_SOURCE_DIR \n" +
+echo "DEPLOY_DIR: $DEPLOY_DIR \n" +
+echo "ANGULAR_PACKAGE_NAME: ${ANGULAR_PACKAGE_NAME} \n" +
+echo "ANGULAR_PACKAGE_TARBALL: ${ANGULAR_PACKAGE_TARBALL} \n" +
+echo "ARTIFACTORY_REPO: ${ARTIFACTORY_REPO} \n" +
+echo "NGINX_VERSION: ${NGINX_VERSION} \n" +
+echo "ARTIFACTORY_TOKEN: ${ARTIFACTORY_TOKEN} \n" +
+echo "BUILD_OUTPUT_PATH: ${BUILD_OUTPUT_PATH} \n"
+
 
 if [ -z "${ANGULAR_PACKAGE_NAME}" ]; then
     echo "Aborting due to ANGULAR_PACKAGE_NAME environment variable is not setted"
@@ -65,6 +68,11 @@ if [ -z "${ARTIFACTORY_TOKEN}" ]; then
     exit 1
 fi
 
+if [ -z "${BUILD_OUTPUT_PATH}" ]; then
+    echo "Aborting due to BUILD_OUTPUT_PATH environment variable is not setted"
+    exit 1
+fi
+
 cd "$LOCAL_SOURCE_DIR"
 
 echo "Retrieving artifact from Artifactory repository"
@@ -81,9 +89,9 @@ if [ $ERR -ne 0 ]; then
     exit $ERR
 fi
 
-if [ -d "$LOCAL_SOURCE_DIR/package/dist" ]; then
+if [ -d "$LOCAL_SOURCE_DIR/package$BUILD_OUTPUT_PATH" ]; then
     #Copying module elements
-    copy_artifacts "package/dist"
+    copy_artifacts "package$BUILD_OUTPUT_PATH"
 else
     echo "Aborting due to error code 1 from copying module elements"
     exit 1
